In [ ]:
print("hello")

hello


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6 , 7 , 8])
result = np.where(arr % 2 == 0, arr, 0)
print(result)
scores = np.array([55, 90, 78, 45, 88, 92, 60])
result = np.where(scores >= 60, scores, 0)
print(result)

[0 2 0 4 0 6 0 8]
[ 0 90 78  0 88 92 60]


In [11]:
scores = np.array([55, 90, 40, 78, 65, 30])
result = np.where(scores < 60, -1, scores)
print(result)

[-1 90 -1 78 65 -1]


In [12]:
temps = np.array([23, 28, 31, 19, 35, 22])

idx = np.where(temps >= 30)
print(type(idx))
print(idx)
print(idx[0])

<class 'tuple'>
(array([2, 4]),)
[2 4]


In [15]:
temps = np.array([23, 28, 31, 19, 35, 22])

idx = np.where(temps >= 30)
print(temps[idx])

[31 35]


In [16]:
fruits = np.array(["사과", "바나나", "사과", "포도", "바나나"])

idx = np.where(fruits == "바나나")
print(idx[0])

[1 4]


In [17]:
arr = np.arange(12)
print(arr)

arr2d = arr.reshape(3, 4)
print(arr2d)

print(arr.reshape(4, 3))

print(arr.reshape(-1, 6))

print(arr2d.reshape(-1))

print(arr.reshape(2, 2, 3))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

print(arr1 * 10)
print(arr1 + 100)

arr2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
arr1d = np.array([10, 20, 30, 40])
aaa = np.array([
    [100],
    [300]
])
print(arr2d + arr1d)
print(arr2d + aaa)

print(arr1 > 2)

print(arr1 ** 2)

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]
[10 20 30]
[101 102 103]
[[11 22 33 44]
 [15 26 37 48]]
[[101 102 103 104]
 [305 306 307 308]]
[False False  True]
[1 4 9]


In [28]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr)

print(arr.sum())

print(arr.sum(axis = 0))

print(arr.sum(axis = 1))

print(arr.mean())
print(arr.max())

print(arr.argmin())
print(arr.argmax())

print(arr.max(axis = 0))
print(arr.min(axis = 0))

print(arr.max(axis = 1))
print(arr.min(axis = 1))

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
3.5
6
0
5
[4 5 6]
[1 2 3]
[3 6]
[1 4]


In [31]:
arr = np.array([30, 10, 20, 50, 40])

sorted_arr = np.sort(arr)
print(sorted_arr)
print(arr)

arr.sort()
print(arr)

arr2 = np.array([30, 10, 20, 50, 40])
print(np.sort(arr2)[::-1])

arr3 = np.array([30, 10, 20])
print(np.argsort(arr3))

names = np.array(['홍길동', '김철수', '이영희'])
scores = np.array([70, 90, 80])
order = np.argsort(scores)
order_desc = np.argsort(scores)[::-1]
print(names[order])
print(scores[order])
print(names[order_desc])
print(scores[order_desc])

[10 20 30 40 50]
[30 10 20 50 40]
[10 20 30 40 50]
[50 40 30 20 10]
[1 2 0]
['홍길동' '이영희' '김철수']
[70 80 90]
['김철수' '이영희' '홍길동']
[90 80 70]


In [35]:
a = np.array([
    [1, 2],
    [3, 4]
])
b = np.array([
    [5, 6],
    [7, 8]
])
print(np.dot(a, b))
print(a @ b)

c = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(c.T)
print(np.transpose(c))

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([[1, 2, 3]])
v4 = np.array([
    [4],
    [5],
    [6]
])
print(np.dot(v1, v2))
print(np.dot(v3, v4))
print(np.dot(v1, v4))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
32
[[32]]
[32]


In [37]:
arr1 = np.array([
    [1, 2],
    [3, 4]
])
arr2 = np.array([
    [5, 6],
    [7, 8]
])
print(np.concatenate([arr1, arr2], axis = 0))
print(np.concatenate([arr1, arr2], axis = 1))
print(np.vstack([arr1, arr2]))
print(np.hstack([arr1, arr2]))

arr3 = np.arange(9)
print(np.array(np.split(arr3, 3)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
scores = np.array([
    [80, 90, 70],
    [60, 75, 85],
    [95, 88, 92],
    [70, 65, 60],
    [88, 92, 79]
])

names = np.array(['철수', '영희', '민수', '지훈', '수연'])

student_avg = scores.mean(axis = 1)
print("학생별 평균:", student_avg)

subject_avg = scores.mean(axis = 0)
print("과목별 평균:", subject_avg)

best_idx = student_avg.argmax()
print(f"최고 평균 학생: {names[best_idx]}")

high_scorers = names[student_avg >= 80]
print("평균 80점 이상 학생:", high_scorers)

order = np.argsort(student_avg)[::-1]
print("평균 높은 순 학생 이름:", names[order])
print("평균 높은 순 점수:", np.round(student_avg[order], 2))

print("전체 최고점:", scores.max())
print("전체 최저점:", scores.min())

학생별 평균: [80.         73.33333333 91.66666667 65.         86.33333333]
과목별 평균: [78.6 82.  77.2]
최고 평균 학생: 민수
평균 80점 이상 학생: ['철수' '민수' '수연']
평균 높은 순 학생 이름: ['민수' '수연' '철수' '영희' '지훈']
평균 높은 순 점수: [91.67 86.33 80.   73.33 65.  ]
전체 최고점: 95
전체 최저점: 60
95
60
